<?php 

$config["css"] = array('bootstrap.min','jquery.cycle2','jquery.fancybox','font-awesome.min','component','gnmenu','styles','bootstrap-responsive');
$config["js"] = array('bootstrap.min','jquery.fancybox','jquery.scrollTo.min','vmouse.min','jquery.animate-enhanced.min','jquery.easing.1.3','map','jquery.validate.min','classie','gnmenu.min','livesearch');

?>

<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="utf-8">
<head>
	<title>LXII | <?php echo $title; ?></title>
	<meta name="description" content="<?php echo $description; ?>" />

	<meta name="keywords" content="professional website design, web design malaysia, malaysia web design, online design firm malaysia, malaysia design studio, web design, logo design, logo, flyer design, flyers design, malaysia logo design, website design kl, webpage design, web design company, graphic design, online design services, malaysia website design" />
	<meta name="author" content="LX2 Design Studio" />
	<base href="http://localhost:8888/">
	<!-- <base href="http://github.localhost/LXII-Ver-Master/public_html/"> -->
	<!-- <base href="http://www.lx2.com.my/"> -->

	<!-- Font -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>

	<!-- Owl Carousel -->
	<link href="owl-carousel/owl.carousel.css" rel="stylesheet">
	<link href="owl-carousel/owl.theme.css" rel="stylesheet">

	<?= links($config["css"],"css"); ?>

	<script language="javascript" type="text/javascript" src="js/jquery.min.js"></script>

	<script src="owl-carousel/owl.carousel.js"></script>
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		{
			"@context" : "http://schema.org",
			"@type" : "LocalBusiness",
			"image" : "http://www.lx2.com.my/img/logo.png",
			"telephone" : "(+60)3-62418948",
			"email" : "services@lx2.com.my",
			"address" : {
				"@type" : "PostalAddress",
				"streetAddress" : "A-6-3A, Casa Idaman",
				"addressRegion" : "KL",
				"addressCountry" : "Malaysia",
				"postalCode" : "51100"
			},
			"review" : {
				"@type" : "Review",
				"author" : {
					"@type" : "Person",
					"name" : "Amelia Au"
				},
				"reviewBody" : "Professional, adaptable, reliable and creative. The team is also friendly and easy to work with. Highly recommended!"
			}
		}
	</script>
</head>
<body>

	<?php

	// discard "?" in the url
	$breadcrumbs = explode("?",$_SERVER["REQUEST_URI"]);
	$breadcrumbs = str_replace("http://www.lx2.com.my/", "", $breadcrumbs);
	$breadcrumbs = str_replace("_", " ", $breadcrumbs);
	// $breadcrumbs = str_replace("/lxii_ver4/public_html", "", $breadcrumbs);
	
	
	// Spli the "/"
	$breadcrumbs = explode("/",$breadcrumbs[0]);
	
	// Discard empty value in array
	$breadcrumbs = array_filter($breadcrumbs);

	$breadcrumb = "";
	foreach ($breadcrumbs as $key => $b) {

		switch ($b) {
			case 'order':
			$friendly_text = 'products';
			break;

			case 'public_html':
			$friendly_text = 'Home';
			break;

			case 'index.php':
			$friendly_text = 'Home';
			break;

			case 'success':
			$friendly_text = 'Payment';
			break;

			case '1':
			$friendly_text = 'Step 1';
			break;

			case '2':
			$friendly_text = 'Step 2';
			break;

			case '3':
			$friendly_text = 'Step 3';
			break;

			case 'project':
			$friendly_text = 'Checkout';
			break;

			default:
			$friendly_text = $b;
			break;
		};

		if ($key != count($breadcrumbs)) {
			if($b=="public_html"){
				$b = "#1";
			};
			$tmp_str = "<a href='$b'>$friendly_text</a>";
		}else{
			
			if(isset($breadcrumbs[2]) && $breadcrumbs[1]=="order"){

				$tmp_str = "<span>".$records[0]->title."</span>";

			} else if(isset($breadcrumbs[2]) && $breadcrumbs[1]=="portfolio") {

				$tmp_str = "<span>".$project[0]->title."</span>";

			} else {

				$tmp_str = "<span>$friendly_text</span>";

			};
		}
		$breadcrumb .= "<li class='breadcrumbs'>".$tmp_str."</li>";
	};

	?>

	<div class='block hide-on-large'></div>

	<ul id="gn-menu" class="gn-menu-main">
		<li class="gn-trigger">

			<a class="gn-icon gn-icon-menu"><span>Menu</span></a>
			<ul id="results"></ul>
			<nav class="gn-menu-wrapper">
				<div class="gn-scroller">
					<ul class="gn-menu">
						<li class="gn-search-item">
							<input placeholder="Search" type="search" class="gn-search">
							<a class="gn-icon gn-icon-search"><span>Search</span></a>
						</li>


						<li>
							<a class="gn-icon gn-icon-thumbs" href="about">About LXII</a>
							<ul class="gn-submenu">
								<!-- <li><a href="mission" class="gn-icon gn-icon-thumbs">Our Mission</a></li> -->
								<li><a class="gn-icon gn-icon-welfare" href="about/society_welfare">Society Welfare</a></li>
							</ul>
						</li>
						<li><a class="gn-icon gn-icon-portfolio" href="portfolio">Porfolio</a></li>
						<li>
							<a class="gn-icon gn-icon-product" href="order">Products</a>
							<ul class="gn-submenu">								
								<li><a class="gn-icon gn-icon-web"  href="order?cat=web">Web</a></li>
								<li><a class="gn-icon gn-icon-graphic"  href="order?cat=print">Graphic</a></li>
								<li><a class="gn-icon gn-icon-branding"  href="order?cat=branding">Branding</a></li>
							</ul>
						</li>
						<li><a class="gn-icon gn-icon-contact" href="contact">Contact</a></li>
					</ul>
				</div><!-- /gn-scroller -->
			</nav>
		</li>
		<li><a href="" id="logo"><img src="img/logo.png" alt="LX2 Design Studio"></a></li>
		<?php echo $breadcrumb ?>
		<li id="call_us_now">
			<script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>
			<div id="SkypeButton_Dropdown_services_268_1">
				<script type="text/javascript">
					Skype.ui({
						"name": "chat",
						"element": "SkypeButton_Dropdown_services_268_1",
						"participants": ["services_268"],
						"imageColor": "blue",
						"imageSize": 24
					});
				</script>
			</div>
		</li>
	</ul>