<?php 

$config["css"] = array('bootstrap.min','jquery.cycle2','jquery.fancybox','font-awesome.min','component','gnmenu','styles','bootstrap-responsive');
$config["js"] = array('bootstrap.min','jquery-mousewheel','jquery.fancybox','jquery.scrollTo.min','vmouse.min','jquery.animate-enhanced.min','jquery.easing.1.3','map','jquery.validate.min','classie','gnmenu.min','livesearch');

$breadcrumbs = explode("?",$_SERVER["REQUEST_URI"]);
$breadcrumbs = str_replace("http://www.lx2.com.my/", "", $breadcrumbs);
$blahzzzz = $breadcrumbs[0];
$breadcrumbs = str_replace("-", " ", $breadcrumbs);

?>

<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="utf-8">
<head prefix=
"og: http://ogp.me/ns# 
fb: http://ogp.me/ns/fb# 
product: http://ogp.me/ns/product#">
<title>LXII | <?php echo $title; ?></title>
<meta name="description" content="<?php echo $description; ?>" />

<?php 
if($this->uri->segment(1) == "order" && $this->uri->segment(2) && $this->uri->segment(2) != "project" && $this->uri->segment(2) != "success"){
	$current_item = $records[0];
	echo "
	<!-- for fb -->
	<meta property='fb:app_id' content='233054770218489' />
	<meta property='og:title' content='LXII | $title' />
	<meta property='og:description' content='$description' />
	<meta property='og:type' content='product' />
	<meta property='og:image' content='http://www.lx2.com.my/img/products/".$this->uri->segment(2).".jpg' />
	<meta property='product:price:amount' content='$current_item->price' />
	<meta property='product:price:currency' content='MYR' />
	<meta property='og:site_name' content='LXII | $title' />
	<meta property='og:url' content='http://www.lx2.com.my$blahzzzz' />
	<!-- end fb -->
	<!-- for twitter -->
	<meta name='twitter:card' content='product'>
	<meta name='twitter:site' content='@lxiidesign'>
	<meta name='twitter:creator' content='@lxiidesign'>
	<meta name='twitter:title' content='$current_item->title'>
	<meta name='twitter:description' content='$current_item->desc'>
	<meta name='twitter:image' content='http://www.lx2.com.my/img/products/$current_item->url.jpg'>
	<meta name='twitter:data1' content='$current_item->price'>
	<meta name='twitter:label1' content='MYR'>
	<meta name='twitter:data2' content='Awesome Result'>
	<meta name='twitter:label2' content='Choose 1 from 2 concepts + Unlimited Amendments'>
	<!-- end for twitter -->
	";
}
?>

<meta name="keywords" content="professional website design, web design malaysia, malaysia web design, online design firm malaysia, malaysia design studio, web design, logo design, logo, flyer design, flyers design, malaysia logo design, website design kl, webpage design, web design company, graphic design, online design services, malaysia website design" />
<meta name="author" content="LX2 Design Studio" />

<!-- <base href="http://localhost:8888/"> -->
<!-- <base href="http://localhost/localhost/LX2New/public_html/"> -->
<base href="http://www.lx2.com.my/">

<!-- Font -->
<link href='http://fonts.googleapis.com/css?family=Raleway:100,400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>

<!-- Owl Carousel -->
<link href="owl-carousel/owl.carousel.css" rel="stylesheet">
<link href="owl-carousel/owl.theme.css" rel="stylesheet">

<?= links($config["css"],"css"); ?>

<script language="javascript" type="text/javascript" src="js/jquery.min.js"></script>

<script src="owl-carousel/owl.carousel.js"></script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
	{
		"@context" : "http://schema.org",
		"@type" : "LocalBusiness",
		"image" : "http://www.lx2.com.my/img/logo.png",
		"telephone" : "(+60)3-62418948",
		"email" : "services@lx2.com.my",
		"address" : {
			"@type" : "PostalAddress",
			"streetAddress" : "A-6-3A, Casa Idaman",
			"addressRegion" : "KL",
			"addressCountry" : "Malaysia",
			"postalCode" : "51100"
		},
		"review" : {
			"@type" : "Review",
			"author" : {
				"@type" : "Person",
				"name" : "Amelia Au"
			},
			"reviewBody" : "Professional, adaptable, reliable and creative. The team is also friendly and easy to work with. Highly recommended!"
		}
	}
</script>
<script type="text/javascript">

		// google-analytics

		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-48201751-1', 'lx2.com.my');
ga('send', 'pageview');


</script>

</head>
<body>

	<?php

	// discard "?" in the url
	$breadcrumbs = explode("?",$_SERVER["REQUEST_URI"]);
	$breadcrumbs = str_replace("http://www.lx2.com.my/", "", $breadcrumbs);
	$breadcrumbs = str_replace("-", " ", $breadcrumbs);
	// $breadcrumbs = str_replace("/lxii_ver4/public_html", "", $breadcrumbs);
	
	
	// Spli the "/"
	$breadcrumbs = explode("/",$breadcrumbs[0]);
	
	// Discard empty value in array
	$breadcrumbs = array_filter($breadcrumbs);

	$breadcrumb = "";
	foreach ($breadcrumbs as $key => $b) {

		switch ($b) {
			case 'order':
			$friendly_text = 'products';
			break;

			case 'public_html':
			$friendly_text = 'Home';
			break;

			case 'index.php':
			$friendly_text = 'Home';
			break;

			case 'success':
			$friendly_text = 'Payment';
			break;

			case '1':
			$friendly_text = 'Step 1';
			break;

			case '2':
			$friendly_text = 'Step 2';
			break;

			case '3':
			$friendly_text = 'Step 3';
			break;

			case 'project':
			$friendly_text = 'Checkout';
			break;

			default:
			$friendly_text = $b;
			break;
		};

		if ($key != count($breadcrumbs)) {
			if($b=="public_html"){
				$b = "#1";
			};
			if ($b == "project"){
				$tmp_str = "<span>$friendly_text</span>";
			} else {
				$tmp_str = "<a href='$b'>$friendly_text</a>";
			};
		}else{
			
			if(isset($breadcrumbs[2]) && $breadcrumbs[1]=="order"){

				$tmp_str = "<span>".$records[0]->title."</span>";

			} else if(isset($breadcrumbs[2]) && $breadcrumbs[1]=="portfolio") {

				$tmp_str = "<span>".$project[0]->title."</span>";

			} else {

				$tmp_str = "<span>$friendly_text</span>";

			};
		}
		$breadcrumb .= "<li class='breadcrumbs'>".$tmp_str."</li>";
	};

	?>

	<div class='block hide-on-large'></div>

	<ul id="gn-menu" class="gn-menu-main">
		<li class="gn-trigger">

			<a class="gn-icon gn-icon-menu"><span>Menu</span></a>
			<ul id="results"></ul>
			<nav class="gn-menu-wrapper">
				<div class="gn-scroller">
					<ul class="gn-menu">
						<li class="gn-search-item">
							<input placeholder="Search" type="search" class="gn-search">
							<a class="gn-icon gn-icon-search"><span>Search</span></a>
						</li>


						<li>
							<a class="gn-icon gn-icon-thumbs" href="about">About LXII</a>
							<ul class="gn-submenu">
								<!-- <li><a href="mission" class="gn-icon gn-icon-thumbs">Our Mission</a></li> -->
								<li><a class="gn-icon gn-icon-welfare" href="about/society-welfare">Society Welfare</a></li>
							</ul>
						</li>
						<li><a class="gn-icon gn-icon-article" href="http://blog.lx2.com.my/" target="_blank">LXII Blog</a></li>
						<li><a class="gn-icon gn-icon-portfolio" href="portfolio">Porfolio</a></li>
						<li>
							<a class="gn-icon gn-icon-product" href="order">Products</a>
							<ul class="gn-submenu">								
								<li><a class="gn-icon gn-icon-web"  href="order?cat=web">Web</a></li>
								<li><a class="gn-icon gn-icon-graphic"  href="order?cat=print">Graphic</a></li>
								<li><a class="gn-icon gn-icon-branding"  href="order?cat=branding">Branding</a></li>
							</ul>
						</li>
						<li><a class="gn-icon gn-icon-contact" href="contact">Contact</a></li>
					</ul>
				</div><!-- /gn-scroller -->
			</nav>
		</li>
		<li><a href="" id="logo"><img src="img/logo.png" alt="LX2 Design Studio"></a></li>
		<?php echo $breadcrumb ?>
		<li id="call_us_now">
			<script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>
			<div id="SkypeButton_Dropdown_services_268_1">
				<script type="text/javascript">
					Skype.ui({
						"name": "chat",
						"element": "SkypeButton_Dropdown_services_268_1",
						"participants": ["services_268"],
						"imageColor": "blue",
						"imageSize": 24
					});
				</script>
			</div>
		</li>
	</ul>